driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true
  enforce_idempotency: true
  multiple_converge: 2
  client_rb:
    count_log_resource_updates: false

verifier:
  name: inspec
  sudo: false

platforms:
  - name: centos-6
    driver:
      box: bento/centos-6.8

  - name: centos-7
    driver:
      box: bento/centos-7.3

  - name: debian-8
    driver:
      box: bento/debian-8.6

  - name: fedora-25
    driver:
      box: bento/fedora-25

  - name: ubuntu-14.04
    driver:
      box: bento/ubuntu-14.04

  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04

suites:
- name: default
  run_list:
    - recipe[test]
